PersonalTrainerPortal/Models/Data/Client.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PersonalTrainerPortal.Models.Data
{
    public class Client
    {
        [Required]
        public int ID { get; set; }
        public string UserID { get; set; }
        [Required, Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Required, Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Required, EmailAddress]
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        
        public string PersonalTrainerID { get; set; }
        

        public List<Workout> Workouts { get; set; }
        public List<Meal> Meals { get; set; }
    }
}

PersonalTrainerPortal/Models/Data/Exercise.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PersonalTrainerPortal.Models.Data
{
    public class Exercise
    {
        [Required]
        public int ID { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]

        public string PersonalTrainerID { get; set; }



    }
}

PersonalTrainerPortal/Models/Data/PersonalTrainer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PersonalTrainerPortal.Models.Data
{
    public class PersonalTrainer
    {
        [Required]
        public int ID { get; set; }
        public string UserID { get; set; }
        [Required, Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Required, Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Required, EmailAddress]
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public List<Exercise> Exercises { get; set; }
        public List<BlogPost> BlogPosts { get; set; }
        public List<Client> Clients { get; set; }
        public List<FoodItem> FoodItems { get; set; }

        //Fields added for Portal Home Customization
        public string Slogan { get; set; }
        public string ProfileDescription { get; set; }
        public string CredentialsDescription { get; set; }
        public string ProductsDescription { get; set; }
        public List<Credential> Credentials { get; set; }
        public List<Offering> Offerings { get; set; }   

    }
}

PersonalTrainerPortal/Models/Data/Workout.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PersonalTrainerPortal.Models.Data
{
    public class Workout
    {
        [Required]
        public int ID { get; set; }
        
        public string Title { get; set; }
        public string Description { get; set; }
        
        public string Type { get; set; }
        
        public string Date { get; set; }
        public int RepCount { get; set; }
        public int SetCount { get; set; }
        public int TimeInterval { get; set; }
        public string Instructions { get; set; }
        public int ExerciseID { get; set; }
        public string ClientID { get; set; }
        public string PersonalTrainerID { get; set; }

    }
}

PersonalTrainerPortal/Models/ExerciseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PersonalTrainerPortal.Models
{
    public class ExerciseViewModel
    {
        
        public string ExerciseTitle { get; set; }
        
        public string ExerciseDescription { get; set; }
        
        public string PersonalTrainerID { get; set; }

        public string VideoTitle { get; set; }
        
        public string VideoDescription { get; set; }
        
        public string VideoURL { get; set; }

        public int ExerciseID { get; set; }

        public bool NullVideoInd { get; set; }

    }
}

PersonalTrainerPortal/Controllers/ClientController.cs
using PersonalTrainerPortal.Models;
using PersonalTrainerPortal.Models.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PersonalTrainerPortal.Controllers
{
    public class ClientController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Client
        public ActionResult Index(string UID)
        {
            //Use Application Cookie from Identity model to find the UID
            if (UID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Client client = db.Clients.Where(c => c.UserID == UID).SingleOrDefault();

            return View(client);
        }

        public ActionResult GetWorkout(string UID)
        {
            //If UID is null - return 404
            //Need to reurn a List of Workouts ordered by date
            List<Workout> workouts = db.Workouts.Where(w => w.ClientID == UID).ToList();

            workouts = workouts.OrderByDescending(w => w.Date).ToList();

            return Json(workouts, JsonRequestBehavior.AllowGet);
        }
    }
}

PersonalTrainerPortal/Controllers/PersonalTrainerController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PersonalTrainerPortal.Models;
using PersonalTrainerPortal.Models.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PersonalTrainerPortal.Controllers
{
    public class PersonalTrainerController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        // GET: PersonalTrainer
        public ActionResult Index(string UID)
        {
            //ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            

            ViewBag.UserLoggedIn = true;

            if (UID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            PersonalTrainer personalTrainer = db.PersonalTrainers.Where(p => p.UserID == UID).SingleOrDefault();

            if (personalTrainer == null)
            {
                return HttpNotFound();
            }
            //personalTrainer.Credentials = db.Credentials.Where(c => c.PersonalTrainerID == personalTrainer.ID).ToList();
            //personalTrainer.Offerings = db.Offerings.Where(o => o.PersonalTrainerID == personalTrainer.ID).ToList();

            return View(personalTrainer);
        }


        public ActionResult Clients(string UID)
        {
            ViewBag.UserLoggedIn = true;

            if (UID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            PersonalTrainer personalTrainer = db.PersonalTrainers.Where(p => p.UserID == UID).SingleOrDefault();
            if (personalTrainer == null)
            {
                return HttpNotFound();
            }
            List<Client> clients = db.Clients.Where(c => c.PersonalTrainerID == personalTrainer.UserID).ToList();

            return View(clients);
        }

        public ActionResult Workout(string UID, string CID)
        {
            ViewBag.UserLoggedIn = true;

            if (UID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (CID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }



            PersonalTrainer personalTrainer = db.PersonalTrainers.Where(p => p.UserID == UID).SingleOrDefault();
            //Return the client by the clientID passed
            Client client = db.Clients.Where(c => c.UserID == CID).SingleOrDefault();

            //Add all exercises tied to the personal trainer
            List<Exercise> exercises = db.Exercises.Where(e => e.PersonalTrainerID == UID).ToList();

            ManageWorkoutViewModel mwvm = new ManageWorkoutViewModel()
            {
                PersonalTrainerID = personalTrainer.UserID,
                ClientID = client.UserID,
                ClientFirstName = client.FirstName,
                ClientLastName = client.LastName,
                ClientEmail = client.Email,
                ClientPhoneNumber = client.PhoneNumber
            };


            return View(mwvm);
        }

        public ActionResult GetExercises(string UID)
        {

            PersonalTrainer personalTrainer = db.PersonalTrainers.Where(p => p.UserID == UID).SingleOrDefault();
            //Get Workouts to Return Model
            if (personalTrainer == null)
            {
                return Json(new { errorMessage = "No Personal Trainer has been found" });
            }

            //Return the ExerciseViewModel based on the Trainer UID
            List<ExerciseViewModel> evmList = new List<ExerciseViewModel>();


            List<Exercise> exercises = new List<Exercise>();
            exercises = db.Exercises.Where(e => e.PersonalTrainerID == UID).ToList();

            //Only add to EVMList if there are exercises for that trainer in the DB
            if (exercises != null)
            {
                foreach (var e in exercises)
                {
                    Video video = db.Videos.Where(v => v.ExerciseID == e.ID).SingleOrDefault();
                    if (video != null)
                    {
                        ExerciseViewModel evm = new ExerciseViewModel()
                        {
                            ExerciseID = e.ID,
                            ExerciseTitle = e.Title,
                            ExerciseDescription = e.Description,
                            VideoTitle = video.Title,
                            VideoDescription = video.Description,
                            VideoURL = video.URL,
                            PersonalTrainerID = e.PersonalTrainerID,
                            NullVideoInd = false
                        };

                        evmList.Add(evm);
                    }

                    if (video == null)
                    {
                        ExerciseViewModel evm = new ExerciseViewModel()
                        {
                            ExerciseID = e.ID,
                            ExerciseTitle = e.Title,
                            ExerciseDescription = e.Description,
                            PersonalTrainerID = e.PersonalTrainerID,
                            NullVideoInd = true
                        };

                        evmList.Add(evm);
                    }
                }

            }

            return Json(evmList, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Details(string UID, string clientID)
        {

            ViewBag.UserLoggedIn = true;

            if (UID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (clientID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            PersonalTrainer personalTrainer = db.PersonalTrainers.Where(p => p.UserID == UID).SingleOrDefault();
            //Return the client by the clientID passed
            Client client = db.Clients.Where(c => c.UserID == clientID).SingleOrDefault();

            if (personalTrainer == null)
            {
                return HttpNotFound();
            }

            return View(client);
        }

        public ActionResult Remove(string UID, string clientID)
        {
            ViewBag.UserLoggedIn = true;


            if (UID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (clientID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            PersonalTrainer personalTrainer = db.PersonalTrainers.Where(p => p.UserID == UID).SingleOrDefault();
            //Return the client by the clientID passed
            Client client = db.Clients.Where(c => c.UserID == clientID).SingleOrDefault();

            if (personalTrainer == null)
            {
                return HttpNotFound();
            }

            return View(client);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Remove")]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveConfirmed(string UID, string clientID)
        {
            PersonalTrainer personalTrainer = db.PersonalTrainers.Where(p => p.UserID == UID).SingleOrDefault();
            Client client = db.Clients.Where(c => c.UserID == clientID).SingleOrDefault();

            client.PersonalTrainerID = null;
            db.SaveChanges();

            return RedirectToAction("Clients", new { UID });
        }


        //GET Exercises
        public ActionResult Exercises(string UID)
        {
            ViewBag.UserLoggedIn = true;

            if (UID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }



            PersonalTrainer personalTrainer = db.PersonalTrainers.Where(p => p.UserID == UID).SingleOrDefault();
            //Get Workouts to Return Model
            if (personalTrainer == null)
            {
                return HttpNotFound();
            }

            //Return the ExerciseViewModel based on the Trainer UID
            List<ExerciseViewModel> evmList = new List<ExerciseViewModel>();


            List<Exercise> exercises = new List<Exercise>();
            exercises = db.Exercises.Where(e => e.PersonalTrainerID == UID).ToList();

            //Only add to EVMList if there are exercises for that trainer in the DB
            if (exercises != null)
            {

                foreach (var e in exercises)
                {

                    Video video = db.Videos.Where(v => v.ExerciseID == e.ID).SingleOrDefault();
                    if (video != null)
                    {
                        ExerciseViewModel evm = new ExerciseViewModel()
                        {
                            ExerciseID = e.ID,
                            ExerciseTitle = e.Title,
                            ExerciseDescription = e.Description,
                            VideoTitle = video.Title,
                            VideoDescription = video.Description,
                            VideoURL = video.URL,
                            PersonalTrainerID = e.PersonalTrainerID,
                            NullVideoInd = false
                        };

                        evmList.Add(evm);
                    }

                    if (video == null)
                    {
                        ExerciseViewModel evm = new ExerciseViewModel()
                        {
                            ExerciseID = e.ID,
                            ExerciseTitle = e.Title,

PersonalTrainerPortal/Views/PersonalTrainer/Clients.cshtml
@model IEnumerable<PersonalTrainerPortal.Models.Data.Client>

@{
    ViewBag.Title = "Clients";
}


<div class="container_styled_1">
    <div class="container margin_60">
        <div class="row">
            <div class="col-md-12">
                <div class="box_style_6">
                    <hr class="styled_2">
                    <div class="indent_title_in">
                        <i class="icon_archive_alt"></i>
                        <h3>My Clients</h3>
                    </div>
                    <div class="wrapper_indent">
                        <div class="table-responsive">
                            
                            <table class="table table-striped">
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Email)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.FirstName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.LastName)
                                    </th>
                                    <th></th>
                                </tr>

                                @foreach (var client in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => client.Email)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => client.FirstName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => client.LastName)
                                        </td>
                                        <td>
                                            @Html.ActionLink("Set Workouts", "Workout", new { UID = client.PersonalTrainerID, CID = client.UserID }) |
                                            @Html.ActionLink("Remove Client", "Remove", new { UID = client.PersonalTrainerID, CID = client.UserID })
                                        </td>
                                    </tr>
                                }

                            </table>
                        </div>
                    </div><!--wrapper_indent -->
                    
                </div>
            </div>

        </div><!--End row -->
    </div><!--End container -->
</div>

PersonalTrainerPortal/Views/PersonalTrainer/Index.cshtml
@model PersonalTrainerPortal.Models.Data.PersonalTrainer

@{
    ViewBag.Title = "Index";
}

<!-- SubHeader =============================================== -->
<section class="parallax_window_in" data-parallax="scroll" data-image-src="/Content/img/sub_header_about.jpg" data-natural-width="1400" data-natural-height="470">
    <div id="sub_content_in">
        <h1>@Model.FirstName @Model.LastName</h1>
        <p>"@Model.Slogan"</p>
    </div>
</section>
<!-- End section -->
<!-- End SubHeader ============================================ -->

<div class="container_styled_1">
    <div class="container margin_60">
        <div class="row">
            <aside class="col-md-3" id="sidebar">
                <div class="theiaStickySidebar">
                    <div class="profile">
                        <p class="text-center"><img src="/Content/img/teacher_2_small.jpg" alt="Teacher" class="img-circle styled_2"></p>
                        <ul class="social_teacher">
                            <li><a href="#"><i class="icon-facebook"></i></a></li>
                            <li><a href="#"><i class="icon-twitter"></i></a></li>
                            <li><a href="#"><i class=" icon-google"></i></a></li>
                        </ul>
                        <ul>
                            <li>Name <strong class="pull-right">@Model.FirstName @Model.LastName</strong> </li>
                            <li>Email <strong class="pull-right">@Model.Email</strong></li>
                            <li>Telephone  <strong class="pull-right">@Model.PhoneNumber</strong></li>
                            <!--<li>Lessons <strong class="pull-right">12</strong></li>
                                <li>Courses <strong class="pull-right">15</strong></li>-->
                        </ul>

                    </div><!-- End box-sidebar -->
                </div>
            </aside>
            <div class="col-md-9">
                <div class="box_style_6">
                    <div class="indent_title_in">
                        <i class="icon_document_alt"></i>
                        <h3>Profile</h3>
                        <p>@Model.Slogan</p>
                    </div>
                    <div class="wrapper_indent">
                        <p>@Model.ProfileDescription</p>
                    @if (Model.Credentials != null)
                    {
                        <h4>Credentials</h4>
                        <p>@Model.CredentialsDescription</p>
                        <div class="row">
                            <div class="col-md-6">
                                <ul class="list_3">
                                    @foreach (var c in Model.Credentials)
                                    {
                                        <li><strong> @c.GraduationYear - @c.Description</strong><p>@c.School - @c.SchoolLocation</p></li>
                                    }


                                </ul>
                            </div>
                            <!--<div class="col-md-6">
                                <ul class="list_3">
                                    <li><strong>September 2009 - Degree in Human Science</strong><p>University of Cambrige - United Kingdom</p></li>
                                    <li><strong>December 2012 - Master course in Pilates</strong><p>University of Cambrige - United Kingdom</p></li>
                                </ul>
                            </div>-->
                        </div><!-- End row-->
                    }
                    </div><!--wrapper_indent -->
                    <hr class="styled_2">
                    <div class="indent_title_in">
                        <i class="icon_archive_alt"></i>
                        <h3>My Products</h3>
                    </div>
                    <div class="wrapper_indent">
                        <p>@Model.ProductsDescription</p>
                        <div class="table-responsive">
                            <table class="table table-striped" id="trainer_courses">
                                <thead>
                                    <tr>
                                        <th>Product</th>
                                        <th>Description</th>
                                        <th>Price</th>
                                        <th>Rate</th>
                                    </tr>
                                </thead>
                                <tbody>
                                   @if (Model.Offerings != null)
                                   {
                                       foreach (var o in Model.Offerings)
                                       {
                                        <tr>
                                            <td>@o.Title</td>
                                            <td><a  href="#">@o.Description</a></td>
                                            <td>@o.Price</td>
                                            <td class="rating_2"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class=" icon-star-empty"></i><i class=" icon-star-empty"></i></td>
                                        </tr>
                                       }
                                   }

                                </tbody>
                            </table>
                        </div>
                    </div><!--wrapper_indent -->
                    <div class="wrapper_indent">
                        @Html.ActionLink("Manage Clients", "Clients", "PersonalTrainer", new { UID = Model.UserID }, new { @class = "btn-link" })<br />
                        @Html.ActionLink("Manage Exercises", "Exercises", "PersonalTrainer", new { UID = Model.UserID }, new { @class = "btn-link" })
                    </div>
                </div>
            </div>

        </div><!--End row -->
    </div><!--End container -->
</div>

PersonalTrainerPortal/Views/PersonalTrainer/Workout.cshtml
@model PersonalTrainerPortal.Models.ManageWorkoutViewModel
@{
    ViewBag.Title = "Workout";
}


<div ng-app="WorkoutModule">
    <div class="container_styled_1">
        <div class="container margin_100_35">
            <div class="col-md-12">
                <div class="profile">
                    <p class="text-center"><img src="/Content/img/teacher_2_small.jpg" alt="Teacher" class="img-circle styled_2"></p>
                    <ul class="social_teacher">
                        <li><a href="#"><i class="icon-facebook"></i></a></li>
                        <li><a href="#"><i class="icon-twitter"></i></a></li>
                        <li><a href="#"><i class=" icon-google"></i></a></li>
                    </ul>
                    <ul>
                        <li>Name <strong class="pull-right">@Model.ClientFirstName @Model.ClientLastName</strong> </li>
                        <li>Email <strong class="pull-right">@Model.ClientEmail</strong></li>
                        <li>Telephone  <strong class="pull-right">@Model.ClientPhoneNumber</strong></li>
                        <li>Height <strong class="pull-right"></strong></li>
                        <li>Weight <strong class="pull-right"></strong></li>
                        <li>Fitness Goals <strong class="pull-right"></strong></li>
                        <!--<li>Lessons <strong class="pull-right">12</strong></li>
                        <li>Courses <strong class="pull-right">15</strong></li>-->
                    </ul>

                </div>

            </div>
        </div>
        <hr />
    </div>


    <div class="container margin_30">
        <div class="row">
            <aside class="col-md-4" id="sidebar" ng-controller="ExerciseController">
                <div class="col-md-12">
                    <div class="box_style_6">
                        <hr class="styled_2">
                        <div>
                            <h3>My Exercises</h3>
                        </div>
                        <div class="menu-wrapper">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <tr>
                                        <th>
                                            Title
                                        </th>
                                    </tr>

                                    <tr ng-repeat="exercise in evmList">
                                        <td>
                                            {{exercise.ExerciseTitle}} <a href="#" data-toggle="modal" data-target="#exercise" id="exerciseButton" class="hidden-xs" ng-click="openExercisePopup(exercise.ExerciseTitle)">Add to Workout</a>
                                        </td>
                                    </tr>
                                </table>
                            </div>

                        </div><!--wrapper_indent -->

                    </div>
                </div>
                <!--Exercise Popup Start-->
                <div class="modal fade" id="exercise" tabindex="-1" role="dialog" aria-labelledby="myExercise" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content modal-popup">
                            <a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
                            @using (Html.BeginForm("AddToWorkout", "PersonalTrainer", new { @class = "popup-form", id = "myExercise" }))
                            {
                                <h3 id="exerciseName">{{ExerciseName}}</h3>
                                <p class="text-danger"><strong>{{errorMessage}}</strong></p>
                                @Html.HiddenFor(model => model.PersonalTrainerID, new { Value = Request.Params[0], @class = "form-control" })
                                @Html.HiddenFor(model => model.ClientID, new { Value = Request.Params[1], @class = "form-control" })
                                @Html.HiddenFor(model => model.ExerciseTitle, new { @class = "form-control", id = "exerciseTitleForm" })
                                <input type="text" class="form-control form-white" id="ExerciseDate" name="ExerciseDate" placeholder="Date">
                                <input type="text" class="form-control form-white" id="ExerciseSetCount" name="ExerciseSetCount" placeholder="Number of Sets">
                                <input type="text" class="form-control form-white" id="ExerciseRepCount" name="ExerciseRepCount" placeholder="Number of Reps">
                                <input type="text" class="form-control form-white" id="ExerciseInstructions" name="ExerciseInstructions" placeholder="Specific Instructions">
                                <button type="submit" class="btn btn-submit" formaction="@Url.Action("AddToWorkout")">Submit</button>
                            }
                        </div>
                    </div>
                </div>
                <!--Exercise Popup End-->
            </aside>
            <div class="col-md-8">
                <div class="box_style_6">
                    <hr class="styled_2">
                    <div class="fc-title">
                        <h3>Workout Calendar</h3>
                    </div>
                    <div ng-controller="WorkoutController">
                        @*<div id='calendar' ui-calendar="uiConfig.calendar" class="calendar" ng-model="eventSources"> </div>*@
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <tr>
                                    <th>
                                        Date
                                    </th>
                                    <th>
                                        Exercise
                                    </th>
                                    <th>
                                        Set Count
                                    </th>
                                    <th>
                                        Rep Count
                                    </th>
                                    <th>
                                        Instructions
                                    </th>
                                </tr>

                                <tr ng-repeat="workout in workouts">
                                    <td>
                                        {{workout.Date | date : shortDate}}
                                    </td>
                                    <td>
                                        {{workout.Title}}
                                    </td>
                                    <td>
                                        {{workout.SetCount}}
                                    </td>
                                    <td>
                                        {{workout.RepCount}}
                                    </td>
                                    <td>
                                        {{workout.Instructions}}
                                    </td>
                                </tr>
                            </table>
                        </div>

                    </div>
                </div><!--wrapper_indent -->

            </div>
        </div><!--End row -->

    </div>
</div><!--End container -->